"""Historical backtest of the directional (buy calls/puts) signal.

Data constraint, and why this backtest looks different from the iron
condor one in `backtest.py`: that backtest only needs daily bars, so it
can run over years of history. This signal is fundamentally intraday --
VWAP, opening-range breakout, and a 5-minute EMA9/21 -- and free intraday
history from yfinance is capped at the last ~60 days for a 5-minute bar
size. There is no way to get a multi-year backtest of this exact rule
from free data. What follows is real, but it is a ~60-day out-of-sample
window, not a rigorous multi-regime backtest -- treat any result here as
"does this have any edge at all right now", not "this is proven over
time".

To keep the backtest honest, every trade is generated by feeding real
historical bars through the *unmodified* production functions
(`analysis.build_snapshot`, `intraday.build_intraday_snapshot`,
`intraday.compute_relative_strength`, `gates.evaluate_gates`,
`direction.build_directional_signal`) -- not a separate re-implementation
that could silently drift from what the live app actually does. At each
intraday bar, the "daily" history fed to `build_snapshot` is truncated to
prior completed days plus a synthetic partial bar for the current day
built only from bars up to and including that timestamp -- exactly what
`build_snapshot` sees live before the session closes, and no more.

What this can't capture:
  - Option premium/IV/theta: trades are scored on the *underlying's*
    stop/target, not a simulated option P&L (there's no free source of
    historical QQQ option chains at all, let alone intraday ones).
  - News/catalyst headlines: there's no way to replay historical RSS feed
    content, so the soft catalyst flag is always empty here. The hard
    gates (scheduled macro event, gap, VIX spike) ARE backtested for real.
  - VIX is only available at daily resolution, so the "current" VIX level
    used for the gate at any intraday timestamp is the prior day's close,
    not a live intraday VIX print.
  - Fills are idealized: a stop/target "hit" exits at exactly that level,
    not a worse real-world fill, and a bar whose range spans both the
    stop and the target is conservatively resolved as the stop being hit
    first.
"""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass, field
from typing import Optional

import numpy as np
import pandas as pd

from .analysis import build_snapshot
from .config import Config
from .direction import build_directional_signal
from .gates import evaluate_gates
from .intraday import build_intraday_snapshot, compute_relative_strength, interval_minutes

MIN_DAILY_HISTORY = 200  # trailing days needed before SMA200/ADX/HV20 stop being NaN


@dataclass
class DirectionalBacktestTrade:
    entry_time: dt.datetime
    exit_time: dt.datetime
    direction: str  # "CALL" or "PUT"
    entry_price: float
    exit_price: float
    stop: float
    target: float
    outcome: str  # "target", "stop", "eod"
    return_pct: float  # signed so positive always means a winning trade
    score: float
    confidence: str


@dataclass
class ConfidenceStats:
    confidence: str
    num_trades: int
    win_rate_pct: float
    expectancy_pct: float


@dataclass
class DirectionalBacktestSummary:
    num_trades: int
    win_rate_pct: float
    avg_win_pct: float
    avg_loss_pct: float
    expectancy_pct: float
    total_return_pct: float
    profit_factor: float
    max_drawdown_pct: float
    calls: int
    puts: int
    by_confidence: list = field(default_factory=list)  # list[ConfidenceStats]


def _partial_day_row(bars_so_far: pd.DataFrame, label: pd.Timestamp) -> pd.Series:
    return pd.Series(
        {
            "Open": float(bars_so_far["Open"].iloc[0]),
            "High": float(bars_so_far["High"].max()),
            "Low": float(bars_so_far["Low"].min()),
            "Close": float(bars_so_far["Close"].iloc[-1]),
            "Volume": float(bars_so_far["Volume"].sum()),
        },
        name=label,
    )


def _simulate_day(
    day: dt.date,
    prior_daily_history: pd.DataFrame,
    prior_vix_history: pd.DataFrame,
    qqq_day_bars: pd.DataFrame,
    spy_day_bars: pd.DataFrame,
    cfg: Config,
) -> list[DirectionalBacktestTrade]:
    if len(prior_daily_history) < MIN_DAILY_HISTORY or prior_vix_history.empty:
        return []

    bar_minutes = interval_minutes(cfg.intraday_interval)
    spy_aligned = spy_day_bars.reindex(qqq_day_bars.index, method="ffill")
    if spy_aligned["Close"].isna().all():
        return []

    prior_close = float(prior_daily_history["Close"].iloc[-1])
    vix_level = float(prior_vix_history["Close"].iloc[-1])

    trades: list[DirectionalBacktestTrade] = []
    in_trade: Optional[dict] = None
    n_bars = len(qqq_day_bars)

    for k in range(n_bars):
        bar = qqq_day_bars.iloc[k]
        timestamp = qqq_day_bars.index[k]

        if in_trade is not None:
            hit_stop = bar["Low"] <= in_trade["stop"] if in_trade["direction"] == "CALL" else bar["High"] >= in_trade["stop"]
            hit_target = bar["High"] >= in_trade["target"] if in_trade["direction"] == "CALL" else bar["Low"] <= in_trade["target"]
            if hit_stop or hit_target:
                # Conservative: a bar spanning both levels resolves as the stop.
                exit_price = in_trade["stop"] if hit_stop else in_trade["target"]
                outcome = "stop" if hit_stop else "target"
                trades.append(_close_trade(in_trade, timestamp, exit_price, outcome))
                in_trade = None
            continue

        bars_so_far_qqq = qqq_day_bars.iloc[: k + 1]
        bars_so_far_spy = spy_aligned.iloc[: k + 1]
        if bars_so_far_spy["Close"].isna().any():
            continue

        partial_row = _partial_day_row(bars_so_far_qqq, pd.Timestamp(day))
        synthetic_daily = pd.concat([prior_daily_history, partial_row.to_frame().T])
        synthetic_vix = pd.concat(
            [prior_vix_history, pd.Series({"Close": vix_level}, name=pd.Timestamp(day)).to_frame().T]
        )

        try:
            daily_snapshot = build_snapshot(synthetic_daily, synthetic_vix, cfg.adx_trend_threshold)
        except Exception:
            continue

        intraday_snapshot = build_intraday_snapshot(bars_so_far_qqq, cfg.opening_range_minutes, bar_minutes)
        relative_strength_pct = compute_relative_strength(bars_so_far_qqq, bars_so_far_spy)

        gap_pct = (float(partial_row["Close"]) / prior_close - 1.0) * 100.0
        gate = evaluate_gates(
            today=day,
            macro_event_dates=cfg.macro_event_dates,
            gap_pct=gap_pct,
            gap_confirmed=True,
            gap_threshold_pct=cfg.gap_threshold_pct,
            vix_level=vix_level,
            vix_spike_threshold=cfg.vix_spike_threshold,
            snapshot=daily_snapshot,
            adx_trend_threshold=cfg.adx_trend_threshold,
            volume_ratio_threshold=cfg.volume_ratio_threshold,
            catalyst_hits=[],  # historical headlines can't be replayed -- see module docstring
        )

        signal = build_directional_signal(daily_snapshot, intraday_snapshot, relative_strength_pct, gate, {}, cfg)
        if signal.bias in ("CALL", "PUT"):
            in_trade = {
                "entry_time": timestamp,
                "direction": signal.bias,
                "entry_price": daily_snapshot.spot,
                "stop": signal.stop_loss_underlying,
                "target": signal.target_underlying,
                "score": signal.score,
                "confidence": signal.confidence,
            }

    if in_trade is not None:
        last_bar = qqq_day_bars.iloc[-1]
        trades.append(_close_trade(in_trade, qqq_day_bars.index[-1], float(last_bar["Close"]), "eod"))

    return trades


def _close_trade(in_trade: dict, exit_time: pd.Timestamp, exit_price: float, outcome: str) -> DirectionalBacktestTrade:
    entry = in_trade["entry_price"]
    if in_trade["direction"] == "CALL":
        return_pct = (exit_price / entry - 1.0) * 100.0
    else:
        return_pct = (entry / exit_price - 1.0) * 100.0
    return DirectionalBacktestTrade(
        entry_time=in_trade["entry_time"],
        exit_time=exit_time,
        direction=in_trade["direction"],
        entry_price=round(entry, 2),
        exit_price=round(exit_price, 2),
        stop=round(in_trade["stop"], 2),
        target=round(in_trade["target"], 2),
        outcome=outcome,
        return_pct=round(return_pct, 4),
        score=in_trade["score"],
        confidence=in_trade["confidence"],
    )


def simulate_directional_backtest(
    daily_history: pd.DataFrame,
    vix_history: pd.DataFrame,
    qqq_intraday: pd.DataFrame,
    spy_intraday: pd.DataFrame,
    cfg: Config,
) -> list[DirectionalBacktestTrade]:
    """Pure simulation -- no network I/O, so this is what the tests exercise
    directly with synthetic data."""
    trades: list[DirectionalBacktestTrade] = []

    qqq_days = sorted({ts.date() for ts in qqq_intraday.index})
    for day in qqq_days:
        qqq_day_bars = qqq_intraday[qqq_intraday.index.date == day]
        spy_day_bars = spy_intraday[spy_intraday.index.date == day]
        if qqq_day_bars.empty or spy_day_bars.empty:
            continue

        prior_daily_history = daily_history[daily_history.index.date < day]
        prior_vix_history = vix_history[vix_history.index.date < day]

        trades.extend(
            _simulate_day(day, prior_daily_history, prior_vix_history, qqq_day_bars, spy_day_bars, cfg)
        )

    return trades


def summarize(trades: list[DirectionalBacktestTrade]) -> DirectionalBacktestSummary:
    if not trades:
        return DirectionalBacktestSummary(
            num_trades=0, win_rate_pct=float("nan"), avg_win_pct=float("nan"), avg_loss_pct=float("nan"),
            expectancy_pct=float("nan"), total_return_pct=0.0, profit_factor=float("nan"),
            max_drawdown_pct=0.0, calls=0, puts=0, by_confidence=[],
        )

    returns = [t.return_pct for t in trades]
    wins = [r for r in returns if r > 0]
    losses = [r for r in returns if r <= 0]

    equity = np.cumsum(returns)
    running_peak = np.maximum.accumulate(equity)
    max_drawdown = float((running_peak - equity).max()) if len(equity) else 0.0

    gross_win = sum(wins)
    gross_loss = abs(sum(losses))

    by_confidence = []
    for label in ("High", "Medium"):
        subset = [t.return_pct for t in trades if t.confidence == label]
        if subset:
            sub_wins = [r for r in subset if r > 0]
            by_confidence.append(
                ConfidenceStats(
                    confidence=label,
                    num_trades=len(subset),
                    win_rate_pct=len(sub_wins) / len(subset) * 100.0,
                    expectancy_pct=sum(subset) / len(subset),
                )
            )

    return DirectionalBacktestSummary(
        num_trades=len(trades),
        win_rate_pct=len(wins) / len(trades) * 100.0,
        avg_win_pct=(sum(wins) / len(wins)) if wins else float("nan"),
        avg_loss_pct=(sum(losses) / len(losses)) if losses else float("nan"),
        expectancy_pct=sum(returns) / len(trades),
        total_return_pct=sum(returns),
        profit_factor=(gross_win / gross_loss) if gross_loss > 0 else float("nan"),
        max_drawdown_pct=max_drawdown,
        calls=sum(1 for t in trades if t.direction == "CALL"),
        puts=sum(1 for t in trades if t.direction == "PUT"),
        by_confidence=by_confidence,
    )


def _fmt(x: float, decimals: int = 2) -> str:
    if x is None or x != x:
        return "n/a"
    return f"{x:.{decimals}f}"


def render_directional_backtest_report(symbol: str, lookback_days: int, summary: DirectionalBacktestSummary) -> str:
    generated_at = dt.datetime.now()
    parts = [
        f"# {symbol} Directional Signal Backtest -- {generated_at.strftime('%Y-%m-%d %H:%M')}",
        "",
        f"> Simulated over the last {lookback_days} days of real 5-minute {symbol}/SPY bars -- the "
        "longest window free intraday data allows. **This is a short out-of-sample check, not a "
        "multi-year, multi-regime backtest.** Scored on the underlying's stop/target only, not "
        "simulated option premium. See the module docstring in "
        "`qqq_iron_condor/directional_backtest.py` for exactly what this can and can't capture. "
        "Not financial advice.",
        "",
    ]

    if summary.num_trades == 0:
        parts.append("_No trades were generated over this backtest window._")
        parts.append("")
        return "\n".join(parts)

    parts.append(f"- **Trades:** {summary.num_trades} ({summary.calls} calls / {summary.puts} puts)")
    parts.append(f"- **Win rate:** {_fmt(summary.win_rate_pct, 1)}%")
    parts.append(f"- **Avg win / avg loss:** {_fmt(summary.avg_win_pct)}% / {_fmt(summary.avg_loss_pct)}%")
    parts.append(f"- **Expectancy (avg return per trade):** {_fmt(summary.expectancy_pct)}%")
    parts.append(f"- **Total return (sum of per-trade %, non-compounded):** {_fmt(summary.total_return_pct)}%")
    parts.append(f"- **Profit factor (gross win / gross loss):** {_fmt(summary.profit_factor, 2)}")
    parts.append(f"- **Max drawdown (equity curve, percentage points):** {_fmt(summary.max_drawdown_pct)}%")
    parts.append("")

    if summary.by_confidence:
        parts.append("| Confidence | Trades | Win rate | Expectancy |")
        parts.append("|---|---|---|---|")
        for c in summary.by_confidence:
            parts.append(f"| {c.confidence} | {c.num_trades} | {_fmt(c.win_rate_pct, 1)}% | {_fmt(c.expectancy_pct)}% |")
        parts.append("")

    parts.append(
        "_A profit factor and expectancy above zero here is weak evidence of an edge over a short, "
        "single-regime window -- not proof. Re-run this periodically as more history accumulates, "
        "and treat a single run's numbers with real skepticism until they're consistent across "
        "several independent windows._"
    )
    parts.append("")

    return "\n".join(parts)


def main(argv=None) -> int:
    import argparse
    import sys
    from pathlib import Path

    from . import data

    parser = argparse.ArgumentParser(description="Backtest the QQQ directional (buy calls/puts) signal")
    parser.add_argument("--lookback-days", type=int, default=59, help="Days of 5-minute history to backtest (yfinance caps this at 60)")
    parser.add_argument("--output-dir", default="reports/backtests", help="Directory to save the report")
    args = parser.parse_args(argv)

    cfg = Config()

    print(f"Fetching {args.lookback_days}d of {cfg.intraday_interval} {cfg.symbol}/{cfg.spy_symbol} history...", file=sys.stderr)
    qqq_intraday = data.get_intraday_history(cfg.symbol, cfg.intraday_interval, f"{args.lookback_days}d")
    spy_intraday = data.get_intraday_history(cfg.spy_symbol, cfg.intraday_interval, f"{args.lookback_days}d")

    print("Fetching daily history for the trend/momentum indicators...", file=sys.stderr)
    daily_history = data.get_price_history(cfg.symbol, "3y")
    vix_history = data.get_vix_history("3y")

    trades = simulate_directional_backtest(daily_history, vix_history, qqq_intraday, spy_intraday, cfg)
    summary = summarize(trades)
    report_md = render_directional_backtest_report(cfg.symbol, args.lookback_days, summary)
    print(report_md)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / f"directional-{dt.date.today().isoformat()}.md"
    out_path.write_text(report_md)
    print(f"\nSaved backtest report to {out_path}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
